- type: replace
  path: /instance_groups/name=windows-worker/jobs/-
  value:
    name: cloud-provider
    release: kubo
    properties:
      cloud-provider:
        type: aws

- type: replace
  path: /instance_groups/name=windows-worker/jobs/name=kubelet-windows/consumes?
  value:
    cloud-provider: {from: worker-cloud-provider}

- type: replace
  path: /instance_groups/name=windows-worker/jobs/name=kubelet-windows/properties/cloud-provider?
  value: aws

- type: replace
  path: /instance_groups/name=windows-worker/jobs/name=kube-proxy-windows/properties/cloud-provider?
  value: aws
