- type: replace
  path: /releases/-
  value:
    name: "windows-utilities"
    version: "0.11.0"
    url: "https://bosh.io/d/github.com/cloudfoundry-incubator/windows-utilities-release?v=0.11.0"
    sha1: "efc10ac0f4acae23637ce2c6f864d20df2e3a781"

- type: replace
  path: /addons/-
  value:
    name: set-pw
    include:
      stemcell:
      - os: windows1803
      - os: windows1903
      - os: windows2019
    jobs:
    - name: enable_rdp
      release: windows-utilities
      properties:
        enable_rdp:
          enabled: true
    - name: enable_ssh
      release: windows-utilities
    - name: set_password
      release: windows-utilities
      properties:
        set_password:
          password: ((windows-rdp-password))
