---
resources:
  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh
      branch: master

  - name: bosh-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment.git
      branch: master

  - name: ubuntu-trusty-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent

  - name: bosh-alpha-compiled-releases
    type: s3
    source:
      bucket: bosh-alpha-compiled-release-tarballs
      access_key_id: ((compiled_aws_key_id))
      secret_access_key: ((compiled_aws_secret_access_key))
      regexp: ".*-(\\d+).tgz"

jobs:
  - name: compile-bosh-release-ubuntu-trusty-3586
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: bosh-src
          trigger: true
        - get: ubuntu-trusty-stemcell
          version:
            version: "3586.7"
      - task: build-release
        file: bosh-deployment/ci/bosh-alpha-compiled-releases/tasks/build-release.yml
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: source-release
      - put: bosh-alpha-compiled-releases
        params:
          file: "compiled-release/*.tgz"
