---
resources:
  - name: bosh-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment.git
      branch: master

  - name: ubuntu-trusty-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent

  - name: bosh-candidate-release-tarballs
    type: s3
    source:
      bucket: bosh-candidate-release-tarballs
      versioned_file: "bosh-dev-release.tgz"

  - name: bosh-alpha-compiled-releases
    type: s3
    source:
      bucket: bosh-alpha-compiled-release-tarballs
      access_key_id: ((compiled_aws_key_id))
      secret_access_key: ((compiled_aws_secret_access_key))
      regexp: ".*-(\\d+).tgz"

jobs:
  - name: compile-bosh-release-ubuntu-trusty-3468
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: bosh-candidate-release-tarballs
          trigger: true
        - get: ubuntu-trusty-stemcell
          version:
            version: "3468.1"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: bosh-candidate-release-tarballs
      - put: bosh-alpha-compiled-releases
        params:
          file: "compiled-release/*.tgz"
