---
resources:
  - name: bosh-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment.git
      branch: {{branch}}

  # releases

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: uaa-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/uaa-release

  # stemcells

  - name: ubuntu-trusty-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent

  # outputs

  - name: compiled-releases
    type: s3
    source:
      bucket: "bosh-compiled-release-tarballs"
      access_key_id: {{aws_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      regexp: ".*-(\\d+).tgz"

jobs:
  - name: compile-bosh-release-260
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: bosh-release
          version:
            version: "260.8"
        - get: ubuntu-trusty-stemcell
          version:
            version: "3363.48"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: bosh-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-bosh-release-261
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: bosh-release
          version:
            version: "261.5"
        - get: ubuntu-trusty-stemcell
          version:
            version: "3363.48"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: bosh-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-uaa-release-24
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: uaa-release
            version:
              version: "24.14"
          - get: ubuntu-trusty-stemcell
            version:
              version: "3363.48"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: uaa-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-uaa-release-30
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: uaa-release
            version:
              version: "30.9"
          - get: ubuntu-trusty-stemcell
            version:
              version: "3363.48"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: uaa-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"
