---
resources:
  - name: bosh-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment.git
      branch: {{branch}}

  # releases

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: uaa-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/uaa-release

  - name: credhub-release
    type: bosh-io-release
    source:
      repository: pivotal-cf/credhub-release

  - name: config-server-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/config-server-release

  - name: warden-cpi
    type: bosh-io-release
    source:
      repository: cppforlife/bosh-warden-cpi-release

  - name: garden-linux
    type: bosh-io-release
    source:
      repository: cloudfoundry/garden-linux-release

  - name: garden-runc
    type: bosh-io-release
    source:
      repository: cloudfoundry/garden-runc-release

  - name: grootfs
    type: bosh-io-release
    source:
      repository: cloudfoundry/grootfs-release

  - name: dns
    type: bosh-io-release
    source:
      repository: cloudfoundry/dns-release

  # stemcells

  - name: ubuntu-trusty-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent

  # outputs

  - name: compiled-releases
    type: s3
    source:
      bucket: "bosh-compiled-release-tarballs"
      access_key_id: {{aws_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      regexp: ".*-(\\d+).tgz"

jobs:
  - name: compile-bosh-release-263-ubuntu-trusty-3445
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: bosh-release
          version:
            version: "263.2.0"
        - get: ubuntu-trusty-stemcell
          version:
            version: "3445.11"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: bosh-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-bosh-release-262-ubuntu-trusty-3421
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: bosh-release
          version:
            version: "262.4"
        - get: ubuntu-trusty-stemcell
          version:
            version: "3421.26"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: bosh-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-bosh-release-261-ubuntu-trusty-3363
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: bosh-release
          version:
            version: "261.5"
        - get: ubuntu-trusty-stemcell
          version:
            version: "3363.37"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: bosh-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-bosh-release-260-ubuntu-trusty-3363
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: bosh-release
            version:
              version: "260.8"
          - get: ubuntu-trusty-stemcell
            version:
              version: "3363.37"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: bosh-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-bosh-release-257-ubuntu-trusty-3363
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: bosh-release
            version:
              version: "257.24"
          - get: ubuntu-trusty-stemcell
            version:
              version: "3363.37"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: bosh-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-bosh-release-255-ubuntu-trusty-3363
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: bosh-release
            version:
              version: "255.14"
          - get: ubuntu-trusty-stemcell
            version:
              version: "3363.37"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: bosh-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-uaa-release-30-ubuntu-trusty-3363
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: uaa-release
            version:
              version: "30.5"
          - get: ubuntu-trusty-stemcell
            version:
              version: "3363.37"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: uaa-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-uaa-release-24-ubuntu-trusty-3363
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: uaa-release
            version:
              version: "24.12"
          - get: ubuntu-trusty-stemcell
            version:
              version: "3363.37"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: uaa-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-uaa-release-13-ubuntu-trusty-3363
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: uaa-release
            version:
              version: "13.17"
          - get: ubuntu-trusty-stemcell
            version:
              version: "3363.37"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: uaa-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-uaa-release-41-ubuntu-trusty-3421
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: uaa-release
            version:
              version: "41"
          - get: ubuntu-trusty-stemcell
            version:
              version: "3421.26"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: uaa-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-uaa-release-45-ubuntu-trusty-3421
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: uaa-release
            version:
              version: "45"
          - get: ubuntu-trusty-stemcell
            version:
              version: "3421.15"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: uaa-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-uaa-release-45-ubuntu-trusty-3445
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: uaa-release
            version:
              version: "45.3"
          - get: ubuntu-trusty-stemcell
            version:
              version: "3445.11"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: uaa-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-uaa-release-50-ubuntu-trusty-3468
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: uaa-release
            version:
              version: "50"
          - get: ubuntu-trusty-stemcell
            version:
              version: "3468"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: uaa-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-uaa-release-52-ubuntu-trusty-3468
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: uaa-release
            version:
              version: "52"
          - get: ubuntu-trusty-stemcell
            version:
              version: "3468"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: uaa-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-credhub-release-1-ubuntu-trusty-3445
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: credhub-release
          version:
            version: "1.3.2"
        - get: ubuntu-trusty-stemcell
          version:
            version: "3445.11"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: credhub-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-credhub-release-1.0.8-ubuntu-trusty-3421
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: credhub-release
          version:
            version: "1.0.8"
        - get: ubuntu-trusty-stemcell
          version:
            version: "3421.26"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: credhub-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-credhub-release-1.3.4-ubuntu-trusty-3445
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: credhub-release
          version:
            version: "1.3.4"
        - get: ubuntu-trusty-stemcell
          version:
            version: "3445.11"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: credhub-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-credhub-release-1.3.4-ubuntu-trusty-3468
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: credhub-release
          version:
            version: "1.3.4"
        - get: ubuntu-trusty-stemcell
          version:
            version: "3468"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: credhub-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-credhub-release-1.5.0-ubuntu-trusty-3468
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: credhub-release
          version:
            version: "1.5.0"
        - get: ubuntu-trusty-stemcell
          version:
            version: "3445.7"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: credhub-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-config-server-release-0-ubuntu-trusty-3445
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: config-server-release
          version:
            version: "0.0.1"
        - get: ubuntu-trusty-stemcell
          version:
            version: "3445.11"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: config-server-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-dns-release-0-ubuntu-trusty-3445
    plan:
      - aggregate:
        - get: bosh-deployment
        - get: dns
          version:
            version: "0.0.4"
        - get: ubuntu-trusty-stemcell
          version:
            version: "3445.11"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: dns
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  # bosh-lite related

  - name: compile-warden-cpi-ubuntu-trusty-3445
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: warden-cpi
            version:
              version: "37"
          - get: ubuntu-trusty-stemcell
            version:
              version: "3445.11"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: warden-cpi
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-garden-linux-ubuntu-trusty-3445
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: garden-linux
            version:
              version: "0.342.0"
          - get: ubuntu-trusty-stemcell
            version:
              version: "3445.11"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: garden-linux
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-garden-runc-ubuntu-trusty-3445
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: garden-runc
            version:
              version: "1.1.1"
          - get: ubuntu-trusty-stemcell
            version:
              version: "3445.11"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: garden-runc
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-garden-runc-1-9-ubuntu-trusty-3445
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: garden-runc
            version:
              version: "1.9.4"
          - get: ubuntu-trusty-stemcell
            version:
              version: "3445.11"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: garden-runc
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"

  - name: compile-grootfs-ubuntu-trusty-3445
    plan:
      - aggregate:
          - get: bosh-deployment
          - get: grootfs
            version:
              version: "0.24.0"
          - get: ubuntu-trusty-stemcell
            version:
              version: "3445.11"
      - task: export-release
        file: bosh-deployment/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: grootfs
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"
