---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: bosh-deployment
  - name: bosh-src

outputs:
  - name: source-release

run:
  path: bosh-deployment/ci/bosh-alpha-compiled-releases/tasks/build-release.sh
