platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-deployment/ci/scripts/build-kubo-release.sh

inputs:
  - name: git-kubo-deployment
  - name: git-kubo-release
  - name: kubo-version
outputs:
  - name: kubo-release
