platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
params:
  GCP_SERVICE_ACCOUNT: 
run:
  path: git-kubo-deployment/ci/scripts/destroy-bosh.sh

inputs:
  - name: git-kubo-deployment
  - name: s3-bosh-state
  - name: s3-bosh-creds
  - name: kubo-lock
