platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
params:
  PR_STATUS:
  PR_REPO: kubo-deployment
run:
  path: git-kubo-deployment/ci/scripts/generate-pr-message.sh

inputs:
- name: git-kubo-deployment
outputs:
- name: pr-slack-message
