platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
params:
  GCP_SERVICE_ACCOUNT: 
run:
  path: git-kubo-deployment/ci/scripts/install-bosh.sh

inputs:
- name: git-kubo-deployment
- name: kubo-lock
outputs:
- name: bosh-state
- name: bosh-creds
