platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
params:
  ROUTING_CF_CLIENT_SECRET:
run:
  path: git-kubo-deployment/ci/scripts/pod-to-pod.sh

inputs:
  - name: git-kubo-deployment
  - name: s3-service-creds
  - name: s3-bosh-creds
  - name: kubo-lock
