package kubo_deployment_tests_test

import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	. "github.com/onsi/ginkgo/extensions/table"
	"path/filepath"
	"fmt"
	"github.com/onsi/gomega/gbytes"
	"os"
)

var _ = Describe("Generate manifest", func() {
	BeforeEach(func() {
		bash.Source(pathToScript("generate_service_manifest"), nil)
		bash.Source("_", func(string) ([]byte, error) {
			return []byte(fmt.Sprintf(`repo_directory() { echo -n "%s"; }`, pathFromRoot(""))), nil
		})
	})

	DescribeTable("with incorrect parameters", func(params []string) {
		status, err := bash.Run("main", params)

		Expect(err).NotTo(HaveOccurred())
		Expect(status).NotTo(Equal(0))
	},
		Entry("no params", []string{}),
		Entry("single parameter", []string{"a"}),
		Entry("three parameters", []string{"a", "b", "c"}),
		Entry("with missing environment", []string{"/missing", "a"}),
	)

	Context("successful manifest generation", func() {
		kuboEnv := filepath.Join(testEnvironmentPath, "test_gcp")
		AfterEach(func() {
			files, _ := filepath.Glob(testEnvironmentPath + "/**/*creds.yml")
			for _, f := range files {
				os.Remove(f)
			}
		})

		DescribeTable("populated properties", func(params []string) {
			status, err := bash.Run("main", []string{kuboEnv, "klingon"})

			Expect(err).NotTo(HaveOccurred())
			Expect(status).To(Equal(0))

			Expect(stdout).To(gbytes.Say(params[0]))
		},
			Entry("deployment name", []string{"\nname: klingon\n"}),
			Entry("stemcell version", []string{"\n  version: stemcell.version\n"}),
			Entry("network name", []string{"\n  networks:\n  - name: network-name\n"}),
			Entry("kubernetes API URL", []string{"\n      kubernetes-api-url: https://a.router.name:101928\n"}),
			Entry("kubernetes external port", []string{"\n      external_kubo_port: 101928\n"}),
			Entry("CF API URL", []string{"\n        api_url: cf.api.url\n"}),
			Entry("CF UAA URL", []string{"\n        uaa_url: cf.uaa.url\n"}),
			Entry("CF Client ID", []string{"\n        uaa_client_id: cf.client.id\n"}),
			Entry("CF Client Secret", []string{"\n        uaa_client_secret: cf.client.secret\n"}),
			Entry("Autogenerated kubelet password", []string{"\n      kubelet-password: [a-z0-9]+\n"}),
			Entry("Autogenerated admin password", []string{"\n      admin-password: [a-z0-9]+\n"}),
		)

		It("should not include the variable setion", func() {
			status, err := bash.Run("main", []string{kuboEnv, "cucumber"})
			Expect(err).NotTo(HaveOccurred())
			Expect(status).To(Equal(0))

			Expect(stdout).NotTo(gbytes.Say("variables:"))
		})

		It("should genrate K8s creds for reuse", func() {
			bash.Run("main", []string{kuboEnv, "generis"})
			_, err := os.Stat(filepath.Join(kuboEnv, "service-generis-creds.yml"))
			Expect(err).NotTo(HaveOccurred())
		})

		It("should reproduce the same manifest on the second run", func() {
			bash.Run("main", []string{kuboEnv, "fort"})

			firstRun := make([]byte, len(stdout.Contents()))
			secondRun := make([]byte, len(stdout.Contents()))

			_, err := stdout.Read(firstRun)
			Expect(err).NotTo(HaveOccurred())

			bash.Run("main", []string{kuboEnv, "fort"})

			_, err = stdout.Read(secondRun)
			Expect(err).NotTo(HaveOccurred())

			Expect(firstRun).To(Equal(secondRun))
		})

		It("generates a manifest without the secrets", func() {
			secretlessEnv := filepath.Join(testEnvironmentPath, "secretless")
			status, err := bash.Run("main", []string{secretlessEnv, "sensors"})
			Expect(err).NotTo(HaveOccurred())
			Expect(status).To(Equal(0))

			Expect(stdout).To(gbytes.Say("\n        uaa_client_secret: \\(\\(routing-cf-client-secret\\)\\)\n"))
		})

		It("uses ops-files to modify the manifest", func() {
			opsfileEnv := filepath.Join(testEnvironmentPath, "with_ops")
			status, err := bash.Run("main", []string{opsfileEnv, "name"})

			Expect(err).NotTo(HaveOccurred())
			Expect(status).To(Equal(0))
			Expect(stdout).To(gbytes.Say("\n  os: MALARIA0\n"))
		})

		It("uses vars-files to modify the manifest", func() {
			opsfileEnv := filepath.Join(testEnvironmentPath, "with_vars")
			status, err := bash.Run("main", []string{opsfileEnv, "name"})
			
			Expect(err).NotTo(HaveOccurred())
			Expect(status).To(Equal(0))
			Expect(stdout).To(gbytes.Say("\n        uaa_client_secret: With turkey drink water\n"))
		})
	})
})
