- type: replace
  path: /instance_groups/name=master/jobs/name=kubernetes-roles/properties/specs?/kubelet?
  value: |
    ---
    kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: kubo:internal:kubelet
    subjects:
    - kind: User
      name: kubelet
      apiGroup: rbac.authorization.k8s.io
    roleRef:
      kind: ClusterRole
      name: system:node
      apiGroup: rbac.authorization.k8s.io
