#!/bin/bash

if [[ ! -f "$1" ]] || [[ ! "$1" =~ director.yml$ ]]; then
	echo 'Please specify the path to director.yml'
	exit 1
fi

sed -i -e 's/^#* *\(routing_mode:.*\)$/# \1/' "$1"
sed -i -e 's/^#* *\(routing_mode:\) *\(iaas\).*$/\1 \2/' "$1"
sed -i -e "s/^\(kubernetes_master_host:\).*\(#.*\)/\1 ${kubernetes_master_host} \2/" "$1"
sed -i -e "s/^\(kubernetes_master_port:\).*\(#.*\)/\1 ${kubernetes_master_port:-8443} \2/" "$1"
sed -i -e "s/^\(master_target_pool:\).*\(#.*\).*$/\1 ${master_target_pool} \2/" "$1"
