#!/bin/bash

if [[ ! -f "$1" ]] || [[ ! "$1" =~ director.yml$ ]]; then
	echo 'Please specify the path to director.yml'
	exit 1
fi

# AWS specific updates
sed -i -e "s/^\(region:\).*\(#.*\)/\1 ${region} \2/" "$1"
sed -i -e "s/^\(az:\).*\(#.*\)/\1 ${zone} \2/" "$1"
sed -i -e "s/^\(subnet_id:\).*\(#.*\)/\1 ${private_subnet_id} \2/" "$1"
sed -i -e "s/^\(default_key_name:\).*\(#.*\)/\1 ${default_key_name} \2/" "$1"
sed -i -e "s/^\(default_security_groups:\).*\(#.*\)/\1 \n- ${default_security_groups} \2/" "$1"
sed -i -e "s/^\(az:\).*\(#.*\)/\1 ${zone} \2/" "$1"
sed -i -e "s/^\(default_key_name:\).*\(#.*\)/\1 ${default_key_name} \2/" "$1"
sed -i -e "s/^\(master_iam_instance_profile:\).*\(#.*\)/\1 ${prefix}-cfcr-master \2/" "$1"
sed -i -e "s/^\(worker_iam_instance_profile:\).*\(#.*\)/\1 ${prefix}-cfcr-worker \2/" "$1"
sed -i -e "s/^\(kubernetes_cluster_tag:\).*\(#.*\)/\1 ${kubernetes_cluster_tag} \2/" "$1"

# Generic updates
sed -i -e "s/^\(internal_ip:\).*\(#.*\)/\1 ${private_subnet_ip_prefix}.252 \2/" "$1"
sed -i -e "s=^\(internal_cidr:\).*\(#.*\)=\1 ${private_subnet_ip_prefix}.0/24 \2=" "$1"
sed -i -e "s/^\(internal_gw:\).*\(#.*\)/\1 ${private_subnet_ip_prefix}.1 \2/" "$1"
sed -i -e "s/^\(director_name:\).*\(#.*\)/\1 ${prefix}-bosh \2/" "$1"
sed -i -e "s/^\(dns_recursor_ip:\).*\(#.*\)/\1 ${private_subnet_ip_prefix}.2 \2/" "$1"
