# frozen_string_literal: true

require 'rspec'
require 'yaml'

RSpec::Matchers.define :include_duration do |expected|
  match do |actual|
    actual["options"]["duration"] == expected
  end
end

describe 'set-certificate-duration.yml' do

  it 'modifies all the certificates generated by the CFCR base manifest' do
    duration = 145200
    manifest_dir = File.expand_path("../manifests", File.dirname(__FILE__))
    bosh_int_output = %x(
      bosh interpolate #{manifest_dir}/cfcr.yml --ops-file \
        #{manifest_dir}/ops-files/set-certificate-duration.yml \
        --var certificate-duration=#{duration}
    )

    yaml = YAML.safe_load(bosh_int_output)
    certificates = yaml["variables"].select { |var| var["type"] == "certificate" }
    expect(certificates).to all(include_duration(duration))
  end
end
