- type: remove
  path: /instance_groups/name=worker/vm_extensions/name=cfcr-worker-iam-properties?

- type: replace
  path: /instance_groups/name=worker/jobs/name=cloud-provider/properties/cloud-provider/aws?
  value:
    access_key_id: ((aws_access_key_id_worker))
    secret_access_key: ((aws_secret_access_key_worker))
