internal_ip: # Internal ip address of the BOSH director. Please select an available ip address in the network you wish to deploy into.

deployments_network: # Network name to deploy service in your cloud config

credhub_encryption_key: # 16 byte number in HEX format: i.e. ABCDEF0123456789ABCDEF0123456789

internal_cidr: # CIDR range that BOSH will deploy to
internal_gw: # internal gateway
kubernetes_master_port: # Port to use for Kubernetes API

director_name: # user friendly Director name
dns_recursor_ip: # DNS IP address for resolving non-BOSH hostnames

stemcell_version: # version of the stemcell used in all Kubo deployments. Quote the version to satisfy YAML parsers
stemcell_url: # path to a stemcell used in all Kubo deployments

credhub_release_url: https://bosh.io/d/github.com/pivotal-cf/credhub-release?v=1.0.0
kubo_release_url: https://storage.googleapis.com/kubo-public/kubo-release-latest.tgz

# routing_mode: haproxy

# IaaS routing mode settings
# Comment this section when using CF routing mode
routing_mode: iaas
kubernetes_master_host: # IP address that can be used to reach the Kubernetes API, usually the address of a load balancer
master_target_pool: # target pool that master nodes will be a part of
worker_target_pool: # target pool that worker nodes will be a part of

# CF routing mode settings
# Uncomment and configure the lines below to leverage CF routing instead of IaaS routing
# routing_mode: cf
# kubernetes_master_host: # Hostname of TCP router. Use `cf domains` to find existing TCP domain. If none exists, see https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#shared-domains for instructions to create one.
# routing-cf-api-url: # TCP routing API URL. In PCF: https://api.<system domain>
# routing-cf-client-id: # Routing UAA client name that will be used to register tcp routes
# routing-cf-uaa-url: # Routing UAA URL In PCF: https://uaa.<system domain>
# routing-cf-app-domain-name: # Cloud Foundry apps domain
# routing-cf-nats-internal-ips: # An array of internal IP address of Cloud Foundry NATS, e.g. [ '1.2.3.4' ]
# routing-cf-nats-username: nats
# routing-cf-nats-port: 4222

# uncomment these fields to configure proxy settings for docker
# http_proxy: # e.g. http://my.proxy.local:73636
# https_proxy: # e.g. https://secure.proxy.local:5566
# no_proxy: # e.g. '1.2.3.4,2.3.4.5'
