internal_ip: # Internal ip address of the BOSH director
bosh_hostname: # Resolvable hostname of your BOSH director

deployments_network: # Network name to deploy service in your cloud config

cf_uaa_url: # URL of your CF UAA. In PCF: https://uaa.<system domain>
cf_url: # URL of your CF API. In PCF: https://api.<system domain>
cf_username: # Your CF username. It is used by ODB.
cf-tcp-router-name: # URL to TCP router. In PCF: tcp.<domain>
routing-cf-api-url: # TCP routing API URL. In PCF: https://api.<system domain>
routing-cf-client-id: # Routing UAA client name that will be used to register tcp routes
routing-cf-uaa-url: # Routing UAA URL In PCF: https://uaa.<system domain>

# we use BOSH 261 since CredHub 0.4 supports only it
# CredHub 0.4 fixes important bug that breaks deployment
bosh_release_url: # URL to latest stable 261 bosh-director release https://s3.amazonaws.com/kubo-public/bosh-dev-release.tgz, or link to a local file
bosh_release_sha1: # SHA1 of latest stable 261 bosh-director release
credhub_encryption_key: # 16 byte number in HEX format: i.e. ABCDEF0123456789ABCDEF0123456789
credhub_release_url: # URL to CredHub release 0.4 https://s3.amazonaws.com/kubo-public/credhub-0.4.0.tgz, or link to local file
etcd_release_url: # URL to kubo etcd release https://s3.amazonaws.com/kubo-public/etcd-85%2Bdev.1.tgz, or link to local file
kubo_release_url: # link to local repository, URL to built kubo release https://s3.amazonaws.com/kubo-public/kubo-release.LATEST.tgz, or link to local file
director_name: # user friendly Director name
dns_recursor_ip: # DNS IP address. Usually the same as gateway, see below
internal_cidr: # CIDR range that BOSH will deploy to
internal_gw: # internal gateway

stemcell_version: # version of the stemcell used in all Kubo deployments
syslog-endpoint: ""

