internal_ip: # Internal ip address of the BOSH director. Please select an available ip address in the network you wish to deploy into.

deployments_network: # Network name to deploy service in your cloud config

internal_cidr: # CIDR range that BOSH will deploy to
internal_gw: # internal gateway

director_name: # user friendly Director name
dns_recursor_ip: # DNS IP address for resolving non-BOSH hostnames

kubo_release_url: https://storage.googleapis.com/kubo-public/kubo-release-latest.tgz

# Proxy routing mode settings
# Uncomment this section when using Proxy routing mode
# routing_mode: proxy
# kubernetes_master_host: # IP address of the HA Proxy master node
# kubernetes_master_port: # Port for kubernetes api-server on HA Proxy master node
# worker_haproxy_ip_addresses: # IP address of the HA Proxy worker node
# worker_haproxy_tcp_frontend_port: # Port that the HA Proxy worker will receive traffic on
# worker_haproxy_tcp_backend_port: # Port that the HA Proxy worker will forward traffic to

# IaaS routing mode settings
# Comment this section when using CF routing mode
routing_mode: iaas
kubernetes_master_host: # IP address that can be used to reach the Kubernetes API, usually the address of a load balancer
kubernetes_master_port: 8443 # Kubernetes API server port
master_target_pool: # target pool that master nodes will be a part of

# CF routing mode settings
# Uncomment and configure the lines below to leverage CF routing instead of IaaS routing
# routing_mode: cf
# kubernetes_master_host: # Hostname of TCP router. Use `cf domains` to find existing TCP domain. If none exists, see https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#shared-domains for instructions to create one.
# kubernetes_master_port: # Port for kubernetes api-server to be registered with the Cloud Foundry TCP router
# routing-cf-api-url: # TCP routing API URL. In PCF: https://api.<system domain>
# routing-cf-client-id: # Routing UAA client name that will be used to register tcp routes
# routing-cf-uaa-url: # Routing UAA URL In PCF: https://uaa.<system domain>
# routing-cf-app-domain-name: # Cloud Foundry apps domain
# routing-cf-nats-internal-ips: # An array of internal IP address of Cloud Foundry NATS, e.g. [ '1.2.3.4' ]
# routing-cf-nats-username: nats
# routing-cf-nats-port: 4222

# uncomment these fields to configure proxy settings for docker
# http_proxy: # e.g. http://my.proxy.local:73636
# https_proxy: # e.g. https://secure.proxy.local:5566
# no_proxy: # e.g. '1.2.3.4,2.3.4.5'
