auth_url: # OpenStack authentication URL
az: # Availability zone
default_key_name: # Name of the SSH key pair
default_security_groups: # List of security groups for the instances
net_id: # OpenStack network identifier
openstack_domain: # OpenStack domain (optional)
openstack_project: # Openstack project name
region: # OpenStack region (optional)
openstack_username: # OpenStack admin username
