auth_url: # OpenStack authentication URL
az1: # Availability zone #1
az2: # Availability zone #2
az3: # Availability zone #3
az4: # Availability zone #4
az5: # Availability zone #5
default_key_name: # Name of the SSH key pair
default_security_groups: # List of security groups for the instances
net_id: # OpenStack network identifier
openstack_domain: # OpenStack domain (optional)
openstack_project: # Openstack project ID
openstack_tenant: # OpenStack tenant (required for multi-tenant environments)
region: # OpenStack region (optional)
openstack_username: # OpenStack admin username

openstack_cpi_release_version: # Openstack CPI Release version
openstack_cpi_release_url: # Openstack CPI Release path
openstack_cpi_release_sha1: # Openstack CPI Release sha1
stemcell_sha1: # Stemcell sha1
uaa_release_version: # UAA Release version
uaa_release_url: # UAA Release path
uaa_release_sha1: # UAA Release sha1
bosh_release_version: # Bosh Release version
bosh_release_url: # Bosh Release path
bosh_release_sha1: # Bosh Release sha1
