#!/bin/bash -e

[ -z "$DEBUG" ] || set -x

if ! which lpass > /dev/null 2>&1
then
  echo "must have lastpass CLI installed" >&2
  exit 1
fi

pipeline_dir=$(dirname "$0")
ssh_key=$(lpass show "Shared-London Services"/london-ci/git-ssh-key --notes)
service_account=$(lpass show "Shared-Kubo/bosh-deployer service key" --notes)

fly --target kubo sync
fly --target kubo set-pipeline --pipeline kubo-deployment \
  --config "${pipeline_dir}/pipeline.yml" \
  --var git-ssh-key="${ssh_key}" \
  --var gcp-service-account="${service_account}"

