- type: replace
  path: /addons?/-
  value:
    name: syslog_forwarder
    jobs:
    - name: syslog_forwarder
      release: syslog
      properties:
        syslog:
          address: ((syslog_address))
          port: ((syslog_port))
          transport: ((syslog_transport))
          forward_files: true

- type: replace
  path: /releases/-
  value:
    name: syslog
    version: "11.3.2"
    url: "https://bosh.io/d/github.com/cloudfoundry/syslog-release?v=11.3.2"
    sha1: "64cf40d44746b50edffa78cb0e0dd6f072fee695"