- type: replace
  path: /instance_groups/-
  value:
      name: haproxy
      instances: 1
      networks:
      - name: ((deployments_network))
      azs: [z1]
      stemcell: trusty
      vm_type: common
      jobs:
      - name: haproxy
        release: haproxy

        properties:
          ha_proxy:
            backend_port: ((haproxy_tcp_backend_port))
            tcp_link_port: ((haproxy_tcp_frontend_port))

- type: replace
  path: /releases/-
  value:
    name: haproxy
    version: latest
