- type: replace
  path: /instance_groups/name=master/jobs/name=cloud-provider/properties/cloud-provider?
  value: &vsphere_cloud_provider
    type: vsphere
    vsphere:
      user: ((vcenter_user))
      password: ((vcenter_password))
      server: ((vcenter_ip))
      insecure-flag: 1
      datacenter: ((vcenter_dc))
      datastore: ((vcenter_ds))
      working-dir: /((vcenter_dc))/vm/((vcenter_vms))/((director_uuid))
- type: replace
  path: /instance_groups/name=worker/jobs/name=cloud-provider/properties/cloud-provider?
  value: *vsphere_cloud_provider
