- type: replace
  path: /instance_groups/-
  value:
      name: worker-haproxy
      instances: 1
      networks:
      - name: ((deployments_network))
      azs: [z1]
      stemcell: trusty
      vm_type: common
      jobs:
      - name: haproxy
        release: haproxy
        consumes:
          tcp_backend:
            from: worker_haproxy
        properties:
          ha_proxy:
            tcp_link_port: 9999 # required, but not used

- type: replace
  path: /instance_groups/name=worker/jobs/name=kubelet/properties/backend_port?
  value: ((worker_haproxy_tcp_backend_port))

- type: replace
  path: /instance_groups/name=worker/jobs/name=kubelet/properties/port?
  value: ((worker_haproxy_tcp_frontend_port))

- type: replace
  path: /releases/name=haproxy?
  value:
    name: haproxy
    version: latest
